version: '3.8'

services:
  app:
    image: openjdk:17-jdk-alpine
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yourdbname
      - SPRING_DATASOURCE_USERNAME=yourdbuser
      - SPRING_DATASOURCE_PASSWORD=yourdbpassword
    command: ./mvnw spring-boot:run
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
